/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comulez_github_encryptlib_Uti */

#ifndef _Included_comulez_github_encryptlib_Uti
#define _Included_comulez_github_encryptlib_Uti
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comulez_github_encryptlib_Uti
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_comulez_github_encryptlib_Uti_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     comulez_github_encryptlib_Uti
 * Method:    stringFromJNI2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_comulez_github_encryptlib_Uti_stringFromJNI2
  (JNIEnv *, jobject);

/*
 * Class:     comulez_github_encryptlib_Uti
 * Method:    AES_ECB_encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_comulez_github_encryptlib_Uti_AES_1ECB_1encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     comulez_github_encryptlib_Uti
 * Method:    AES_ECB_encrypt_byte
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_comulez_github_encryptlib_Uti_AES_1ECB_1encrypt_1byte
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     comulez_github_encryptlib_Uti
 * Method:    AES_ECB_decrypt_byte
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_comulez_github_encryptlib_Uti_AES_1ECB_1decrypt_1byte
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
